[package]
name = "ruuvi-prometheus-rs"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.140"
tokio = { version = "1.43.1", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0.218", features = ["derive"] }
prometheus_exporter = { version = "0.8.5" }
compile-time = "0.2.0"
ruuvi-decoders = "1.0.0"
bluer = { version = "0.17.4", features = ["bluetoothd", "tokio-stream"] }
futures = "0.3.31"
