on: [push]

name: Cargo

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config
      - name: Update rust
        run: rustup update

      - name: Run cargo fmt
        run: cargo fmt --check

      - name: Run cargo check
        run: cargo check --all-targets --all-features

      - name: Install clippy
        run: rustup component add clippy
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features

      - name: Run cargo audit
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
